services:
  - type: web
    name: socmarket-backend
    env: java
    plan: free
    buildCommand: "./gradlew build"
    startCommand: "java -jar build/libs/socmarket-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.bktslgouplqkhlwgsxwf.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: postgres
