# Logs
# logging:
#   level:
#     root: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  application:
    name: SOC Market
    
# Configuration de la base de données PostgreSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      idle-timeout: 600000
      pool-name: SocMarketHikariCP
      max-lifetime: 3600000
      connection-timeout: 30000
      validation-timeout: 5000
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      allow-pool-suspension: false

  # Configuration Hibernate et JPA
  jpa:
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.springframework.boot.orm.jpa.hibernate.SpringJtaPlatform
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true
      format-sql: true
    open-in-view: false